server:
  port: 9527

spring:
  application:
    name: cloud-gateway   #eureka 上的服务名
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名字进行路由
      routes:
        - id: payment_routh   #payment _routh  路由的id，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供路由服务地址
          predicates:
              - Path=/payment/getpayment/**    #断言，路由相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
           #- After=2020-10-15T10:15:11.719+08:00[Asia/Shanghai]  #在这个时间以后访问上面的方法才有效，同理befor在什么之前。产品定什么时候上线
           # - Cookie=username,zzyy  #带着cookie
           #- Header=X-Request-Id,\d+    #请求头要有X-Request-Id属性并且值为正数的正则表达式



eureka:
  instance:
    hostname: cloud-gateway-service  #让eureka把鼠标指针放在名字上时，显示的是你现在命名的
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
